- name: Ansible Playbook to Install and Setup Apache on Linux
  hosts: webservers
  become: yes
  tasks:
    - name: Install latest version of Apache
      apt: name=apache2 update_cache=yes state=latest
      when: ansible_os_family == "Debian"

    - name: change port of apache
      lineinfile: 
        path: /etc/apache2/ports.conf
        regexp: "^Listen"
        line: "Listen 8090"
      when: ansible_os_family == "Debian"

    - name: change port of apache
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: "^Listen"
        line: "Listen 8090"
      when: ansible_os_family == "CentOS"


    - name: Install latest version of Apache
      yum: name=httpd update_cache=yes state=latest
      when: ansible_os_family == "CentOS"


    - name: Create document root for domain configured in host variable
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'
 
    - name: Copy your index file
      template:
        src: "files/index-template.html"
        dest: "/var/www/{{ http_host }}/index.html"
 
    - name: Set up virtuahHost
      template:
        src: "files/apache-template.conf"
        dest: "/etc/apache2/sites-available/{{ http_conf }}"
      when: ansible_os_family == "Debian"

 
    - name: Enable site
      command: a2ensite {{ http_conf }}
      notify: restart-apache-deb
      when: ansible_os_family == "Debian"


    - name: "open CENTOS firewall"
      ansible.posix.firewalld:
        service: http
        state: enabled
        immediate: true
        permanent: true
      when: ansible_os_family == "CentOS"

    - name: "UFW firewall allow HTTP on port {{ http_port }}"
      ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp
      when: ansible_os_family == "Debian"
 
  handlers:
    - name: restart-apache-deb
      service:
        name: apache2
        state: restarted

    - name: restart-apache-rhel
      service:
        name: httpd
        state: restarted

